name: Go Build & Docker Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

permissions:
  contents: read

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
          cache-dependency-path: "*.sum"

      - name: Run Go Build
        working-directory: ""
        run: go build -v "./..."

      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: ""
          version: latest

      - name: StaticCheck
        uses: dominikh/staticcheck-action@v1
        with:
          working-directory: ""
          version: latest

      - name: Run format-check
        working-directory: ""
        run: |
          UNFORMATTED=$(gofmt -l .)
          if [ -n "$UNFORMATTED" ]; then
            echo "The following files are not formatted according to gofmt:"
            echo "$UNFORMATTED"
            exit 1
          fi
